<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>

        <TargetFramework>netcoreapp3.0</TargetFramework>

        <RootNamespace>PatHead.StorageService.Util.Test</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.7"/>
        <PackageReference Include="PatHead.Basic.Util" Version="0.0.0.10"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\PatHead.StorageService.Util\PatHead.StorageService.Util.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="test_pic_1.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.json">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
